version: "3"
services:
  app:
    build: .
    container_name: "graphql-ruby-demo"
    ports:
      - "3000:3000"
    command: bundle exec puma
    volumes:
      - .:/home/graphql-ruby-demo
      - bundle-data:/bundle
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  bundle-data:
  db-data:
